name: Node.js Package

on:
  release:
    types:
      - published

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: yarn install --frozen-lockfile
      - run: yarn publish --non-interactive
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}

  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Commit
        run: |
          rm docs/.gitignore
          git config user.name "$GIT_USER_NAME"
          git config user.email "$GIT_USER_EMAIL"
          git add .
          git commit -m "v$(node -pe require\(\"./package.json\"\).version)"
        env:
          GIT_USER_NAME: ${{ secrets.git_user_name }}
          GIT_USER_EMAIL: ${{ secrets.git_user_email }}
      - name: Filter
        run: git filter-branch --prune-empty --subdirectory-filter docs HEAD
      - name: Push
        run: git push --force https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GH_PAGES_REPOSITORY}.git HEAD:${GH_PAGES_BRANCH}
        env:
          GITHUB_TOKEN: ${{ secrets.gh_pages_token }}
          GH_PAGES_REPOSITORY: ${{ secrets.gh_pages_repository }}
          GH_PAGES_BRANCH: master
