name: Node.js Package

on:
  release:
    types:
      - published

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm version ${GITHUB_REF:1}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}

  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - run: |
          npx vuepress build docs
          cd docs/.vuepress/dist
          git init
          git add -A
          git commit -m 'deploy'
          git push -f https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GH_PAGES_REPOSITORY}.git ${GH_PAGES_BRANCH}
        env:
          GITHUB_TOKEN: ${{ secrets.gh_pages_token }}
          GH_PAGES_REPOSITORY: ${{ secrets.gh_pages_repository }}
          GH_PAGES_BRANCH: master
